export const FETCH_ADDRESS_REQUEST = 'FETCH_ADDRESS_REQUEST';
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS';
export const FETCH_ADDRESS_FAILURE = 'FETCH_ADDRESS_FAILURE';

export const FETCH_ROUTE_REQUEST = "FETCH_ROUTE_REQUEST";
export const FETCH_ROUTE_SUCCESS = "FETCH_ROUTE_SUCCESS";
export const FETCH_ROUTE_FAILURE = "FETCH_ROUTE_FAILURE";

export const CLEAR_ORDER = `CLEAR_ORDER`;